// Code generated by protoc-gen-go. DO NOT EDIT.
// source: driver.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ObjectValue struct {
	Props                map[string]*Value `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ObjectValue) Reset()         { *m = ObjectValue{} }
func (m *ObjectValue) String() string { return proto.CompactTextString(m) }
func (*ObjectValue) ProtoMessage()    {}
func (*ObjectValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{0}
}
func (m *ObjectValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectValue.Unmarshal(m, b)
}
func (m *ObjectValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectValue.Marshal(b, m, deterministic)
}
func (dst *ObjectValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectValue.Merge(dst, src)
}
func (m *ObjectValue) XXX_Size() int {
	return xxx_messageInfo_ObjectValue.Size(m)
}
func (m *ObjectValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectValue.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectValue proto.InternalMessageInfo

func (m *ObjectValue) GetProps() map[string]*Value {
	if m != nil {
		return m.Props
	}
	return nil
}

type ArrayValue struct {
	Items                []*Value `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrayValue) Reset()         { *m = ArrayValue{} }
func (m *ArrayValue) String() string { return proto.CompactTextString(m) }
func (*ArrayValue) ProtoMessage()    {}
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{1}
}
func (m *ArrayValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayValue.Unmarshal(m, b)
}
func (m *ArrayValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayValue.Marshal(b, m, deterministic)
}
func (dst *ArrayValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayValue.Merge(dst, src)
}
func (m *ArrayValue) XXX_Size() int {
	return xxx_messageInfo_ArrayValue.Size(m)
}
func (m *ArrayValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayValue.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayValue proto.InternalMessageInfo

func (m *ArrayValue) GetItems() []*Value {
	if m != nil {
		return m.Items
	}
	return nil
}

type Value struct {
	// Types that are valid to be assigned to TestValue:
	//	*Value_I
	//	*Value_U
	//	*Value_F
	//	*Value_S
	//	*Value_B
	//	*Value_O
	//	*Value_A
	//	*Value_Any
	//	*Value_Variable
	//	*Value_Nil
	TestValue            isValue_TestValue `protobuf_oneof:"test_value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{2}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_TestValue interface {
	isValue_TestValue()
}

type Value_I struct {
	I int64 `protobuf:"varint,1,opt,name=i,proto3,oneof"`
}

type Value_U struct {
	U uint64 `protobuf:"varint,2,opt,name=u,proto3,oneof"`
}

type Value_F struct {
	F float64 `protobuf:"fixed64,3,opt,name=f,proto3,oneof"`
}

type Value_S struct {
	S string `protobuf:"bytes,4,opt,name=s,proto3,oneof"`
}

type Value_B struct {
	B bool `protobuf:"varint,5,opt,name=b,proto3,oneof"`
}

type Value_O struct {
	O *ObjectValue `protobuf:"bytes,6,opt,name=o,proto3,oneof"`
}

type Value_A struct {
	A *ArrayValue `protobuf:"bytes,7,opt,name=a,proto3,oneof"`
}

type Value_Any struct {
	Any []byte `protobuf:"bytes,8,opt,name=any,proto3,oneof"`
}

type Value_Variable struct {
	Variable string `protobuf:"bytes,9,opt,name=variable,proto3,oneof"`
}

type Value_Nil struct {
	Nil bool `protobuf:"varint,10,opt,name=nil,proto3,oneof"`
}

func (*Value_I) isValue_TestValue() {}

func (*Value_U) isValue_TestValue() {}

func (*Value_F) isValue_TestValue() {}

func (*Value_S) isValue_TestValue() {}

func (*Value_B) isValue_TestValue() {}

func (*Value_O) isValue_TestValue() {}

func (*Value_A) isValue_TestValue() {}

func (*Value_Any) isValue_TestValue() {}

func (*Value_Variable) isValue_TestValue() {}

func (*Value_Nil) isValue_TestValue() {}

func (m *Value) GetTestValue() isValue_TestValue {
	if m != nil {
		return m.TestValue
	}
	return nil
}

func (m *Value) GetI() int64 {
	if x, ok := m.GetTestValue().(*Value_I); ok {
		return x.I
	}
	return 0
}

func (m *Value) GetU() uint64 {
	if x, ok := m.GetTestValue().(*Value_U); ok {
		return x.U
	}
	return 0
}

func (m *Value) GetF() float64 {
	if x, ok := m.GetTestValue().(*Value_F); ok {
		return x.F
	}
	return 0
}

func (m *Value) GetS() string {
	if x, ok := m.GetTestValue().(*Value_S); ok {
		return x.S
	}
	return ""
}

func (m *Value) GetB() bool {
	if x, ok := m.GetTestValue().(*Value_B); ok {
		return x.B
	}
	return false
}

func (m *Value) GetO() *ObjectValue {
	if x, ok := m.GetTestValue().(*Value_O); ok {
		return x.O
	}
	return nil
}

func (m *Value) GetA() *ArrayValue {
	if x, ok := m.GetTestValue().(*Value_A); ok {
		return x.A
	}
	return nil
}

func (m *Value) GetAny() []byte {
	if x, ok := m.GetTestValue().(*Value_Any); ok {
		return x.Any
	}
	return nil
}

func (m *Value) GetVariable() string {
	if x, ok := m.GetTestValue().(*Value_Variable); ok {
		return x.Variable
	}
	return ""
}

func (m *Value) GetNil() bool {
	if x, ok := m.GetTestValue().(*Value_Nil); ok {
		return x.Nil
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_I)(nil),
		(*Value_U)(nil),
		(*Value_F)(nil),
		(*Value_S)(nil),
		(*Value_B)(nil),
		(*Value_O)(nil),
		(*Value_A)(nil),
		(*Value_Any)(nil),
		(*Value_Variable)(nil),
		(*Value_Nil)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// test_value
	switch x := m.TestValue.(type) {
	case *Value_I:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.I))
	case *Value_U:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.U))
	case *Value_F:
		b.EncodeVarint(3<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.F))
	case *Value_S:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.S)
	case *Value_B:
		t := uint64(0)
		if x.B {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Value_O:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.O); err != nil {
			return err
		}
	case *Value_A:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.A); err != nil {
			return err
		}
	case *Value_Any:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Any)
	case *Value_Variable:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Variable)
	case *Value_Nil:
		t := uint64(0)
		if x.Nil {
			t = 1
		}
		b.EncodeVarint(10<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("Value.TestValue has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // test_value.i
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestValue = &Value_I{int64(x)}
		return true, err
	case 2: // test_value.u
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestValue = &Value_U{x}
		return true, err
	case 3: // test_value.f
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.TestValue = &Value_F{math.Float64frombits(x)}
		return true, err
	case 4: // test_value.s
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestValue = &Value_S{x}
		return true, err
	case 5: // test_value.b
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestValue = &Value_B{x != 0}
		return true, err
	case 6: // test_value.o
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ObjectValue)
		err := b.DecodeMessage(msg)
		m.TestValue = &Value_O{msg}
		return true, err
	case 7: // test_value.a
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ArrayValue)
		err := b.DecodeMessage(msg)
		m.TestValue = &Value_A{msg}
		return true, err
	case 8: // test_value.any
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.TestValue = &Value_Any{x}
		return true, err
	case 9: // test_value.variable
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestValue = &Value_Variable{x}
		return true, err
	case 10: // test_value.nil
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestValue = &Value_Nil{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// test_value
	switch x := m.TestValue.(type) {
	case *Value_I:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.I))
	case *Value_U:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.U))
	case *Value_F:
		n += 1 // tag and wire
		n += 8
	case *Value_S:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.S)))
		n += len(x.S)
	case *Value_B:
		n += 1 // tag and wire
		n += 1
	case *Value_O:
		s := proto.Size(x.O)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_A:
		s := proto.Size(x.A)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_Any:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Any)))
		n += len(x.Any)
	case *Value_Variable:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Variable)))
		n += len(x.Variable)
	case *Value_Nil:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{3}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Function struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Function) Reset()         { *m = Function{} }
func (m *Function) String() string { return proto.CompactTextString(m) }
func (*Function) ProtoMessage()    {}
func (*Function) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{4}
}
func (m *Function) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Function.Unmarshal(m, b)
}
func (m *Function) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Function.Marshal(b, m, deterministic)
}
func (dst *Function) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Function.Merge(dst, src)
}
func (m *Function) XXX_Size() int {
	return xxx_messageInfo_Function.Size(m)
}
func (m *Function) XXX_DiscardUnknown() {
	xxx_messageInfo_Function.DiscardUnknown(m)
}

var xxx_messageInfo_Function proto.InternalMessageInfo

func (m *Function) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TypeRef struct {
	// Types that are valid to be assigned to TestTyperef:
	//	*TypeRef_Name
	//	*TypeRef_NonNull
	//	*TypeRef_List
	TestTyperef          isTypeRef_TestTyperef `protobuf_oneof:"test_typeref"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TypeRef) Reset()         { *m = TypeRef{} }
func (m *TypeRef) String() string { return proto.CompactTextString(m) }
func (*TypeRef) ProtoMessage()    {}
func (*TypeRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{5}
}
func (m *TypeRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeRef.Unmarshal(m, b)
}
func (m *TypeRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeRef.Marshal(b, m, deterministic)
}
func (dst *TypeRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeRef.Merge(dst, src)
}
func (m *TypeRef) XXX_Size() int {
	return xxx_messageInfo_TypeRef.Size(m)
}
func (m *TypeRef) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeRef.DiscardUnknown(m)
}

var xxx_messageInfo_TypeRef proto.InternalMessageInfo

type isTypeRef_TestTyperef interface {
	isTypeRef_TestTyperef()
}

type TypeRef_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type TypeRef_NonNull struct {
	NonNull *TypeRef `protobuf:"bytes,2,opt,name=nonNull,proto3,oneof"`
}

type TypeRef_List struct {
	List *TypeRef `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

func (*TypeRef_Name) isTypeRef_TestTyperef() {}

func (*TypeRef_NonNull) isTypeRef_TestTyperef() {}

func (*TypeRef_List) isTypeRef_TestTyperef() {}

func (m *TypeRef) GetTestTyperef() isTypeRef_TestTyperef {
	if m != nil {
		return m.TestTyperef
	}
	return nil
}

func (m *TypeRef) GetName() string {
	if x, ok := m.GetTestTyperef().(*TypeRef_Name); ok {
		return x.Name
	}
	return ""
}

func (m *TypeRef) GetNonNull() *TypeRef {
	if x, ok := m.GetTestTyperef().(*TypeRef_NonNull); ok {
		return x.NonNull
	}
	return nil
}

func (m *TypeRef) GetList() *TypeRef {
	if x, ok := m.GetTestTyperef().(*TypeRef_List); ok {
		return x.List
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TypeRef) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TypeRef_OneofMarshaler, _TypeRef_OneofUnmarshaler, _TypeRef_OneofSizer, []interface{}{
		(*TypeRef_Name)(nil),
		(*TypeRef_NonNull)(nil),
		(*TypeRef_List)(nil),
	}
}

func _TypeRef_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TypeRef)
	// test_typeref
	switch x := m.TestTyperef.(type) {
	case *TypeRef_Name:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Name)
	case *TypeRef_NonNull:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NonNull); err != nil {
			return err
		}
	case *TypeRef_List:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.List); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TypeRef.TestTyperef has unexpected type %T", x)
	}
	return nil
}

func _TypeRef_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TypeRef)
	switch tag {
	case 1: // test_typeref.name
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestTyperef = &TypeRef_Name{x}
		return true, err
	case 2: // test_typeref.nonNull
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TypeRef)
		err := b.DecodeMessage(msg)
		m.TestTyperef = &TypeRef_NonNull{msg}
		return true, err
	case 3: // test_typeref.list
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TypeRef)
		err := b.DecodeMessage(msg)
		m.TestTyperef = &TypeRef_List{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TypeRef_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TypeRef)
	// test_typeref
	switch x := m.TestTyperef.(type) {
	case *TypeRef_Name:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Name)))
		n += len(x.Name)
	case *TypeRef_NonNull:
		s := proto.Size(x.NonNull)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TypeRef_List:
		s := proto.Size(x.List)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResponsePath struct {
	Key                  *Value        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Prev                 *ResponsePath `protobuf:"bytes,2,opt,name=prev,proto3" json:"prev,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponsePath) Reset()         { *m = ResponsePath{} }
func (m *ResponsePath) String() string { return proto.CompactTextString(m) }
func (*ResponsePath) ProtoMessage()    {}
func (*ResponsePath) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{6}
}
func (m *ResponsePath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePath.Unmarshal(m, b)
}
func (m *ResponsePath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePath.Marshal(b, m, deterministic)
}
func (dst *ResponsePath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePath.Merge(dst, src)
}
func (m *ResponsePath) XXX_Size() int {
	return xxx_messageInfo_ResponsePath.Size(m)
}
func (m *ResponsePath) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePath.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePath proto.InternalMessageInfo

func (m *ResponsePath) GetKey() *Value {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ResponsePath) GetPrev() *ResponsePath {
	if m != nil {
		return m.Prev
	}
	return nil
}

type Variable struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Variable) Reset()         { *m = Variable{} }
func (m *Variable) String() string { return proto.CompactTextString(m) }
func (*Variable) ProtoMessage()    {}
func (*Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{7}
}
func (m *Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Variable.Unmarshal(m, b)
}
func (m *Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Variable.Marshal(b, m, deterministic)
}
func (dst *Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Variable.Merge(dst, src)
}
func (m *Variable) XXX_Size() int {
	return xxx_messageInfo_Variable.Size(m)
}
func (m *Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_Variable proto.InternalMessageInfo

func (m *Variable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type VariableDefinition struct {
	Variable             *Variable `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
	DefaultValue         *Value    `protobuf:"bytes,2,opt,name=defaultValue,proto3" json:"defaultValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VariableDefinition) Reset()         { *m = VariableDefinition{} }
func (m *VariableDefinition) String() string { return proto.CompactTextString(m) }
func (*VariableDefinition) ProtoMessage()    {}
func (*VariableDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{8}
}
func (m *VariableDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariableDefinition.Unmarshal(m, b)
}
func (m *VariableDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariableDefinition.Marshal(b, m, deterministic)
}
func (dst *VariableDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariableDefinition.Merge(dst, src)
}
func (m *VariableDefinition) XXX_Size() int {
	return xxx_messageInfo_VariableDefinition.Size(m)
}
func (m *VariableDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_VariableDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_VariableDefinition proto.InternalMessageInfo

func (m *VariableDefinition) GetVariable() *Variable {
	if m != nil {
		return m.Variable
	}
	return nil
}

func (m *VariableDefinition) GetDefaultValue() *Value {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

type Directive struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments            map[string]*Value `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Directive) Reset()         { *m = Directive{} }
func (m *Directive) String() string { return proto.CompactTextString(m) }
func (*Directive) ProtoMessage()    {}
func (*Directive) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{9}
}
func (m *Directive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Directive.Unmarshal(m, b)
}
func (m *Directive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Directive.Marshal(b, m, deterministic)
}
func (dst *Directive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Directive.Merge(dst, src)
}
func (m *Directive) XXX_Size() int {
	return xxx_messageInfo_Directive.Size(m)
}
func (m *Directive) XXX_DiscardUnknown() {
	xxx_messageInfo_Directive.DiscardUnknown(m)
}

var xxx_messageInfo_Directive proto.InternalMessageInfo

func (m *Directive) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Directive) GetArguments() map[string]*Value {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type FragmentDefinition struct {
	Directives           []*Directive          `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`
	TypeCondition        *TypeRef              `protobuf:"bytes,2,opt,name=typeCondition,proto3" json:"typeCondition,omitempty"`
	SelectionSet         []*Selection          `protobuf:"bytes,3,rep,name=selectionSet,proto3" json:"selectionSet,omitempty"`
	VariableDefinitions  []*VariableDefinition `protobuf:"bytes,4,rep,name=variableDefinitions,proto3" json:"variableDefinitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FragmentDefinition) Reset()         { *m = FragmentDefinition{} }
func (m *FragmentDefinition) String() string { return proto.CompactTextString(m) }
func (*FragmentDefinition) ProtoMessage()    {}
func (*FragmentDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{10}
}
func (m *FragmentDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentDefinition.Unmarshal(m, b)
}
func (m *FragmentDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentDefinition.Marshal(b, m, deterministic)
}
func (dst *FragmentDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentDefinition.Merge(dst, src)
}
func (m *FragmentDefinition) XXX_Size() int {
	return xxx_messageInfo_FragmentDefinition.Size(m)
}
func (m *FragmentDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentDefinition proto.InternalMessageInfo

func (m *FragmentDefinition) GetDirectives() []*Directive {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *FragmentDefinition) GetTypeCondition() *TypeRef {
	if m != nil {
		return m.TypeCondition
	}
	return nil
}

func (m *FragmentDefinition) GetSelectionSet() []*Selection {
	if m != nil {
		return m.SelectionSet
	}
	return nil
}

func (m *FragmentDefinition) GetVariableDefinitions() []*VariableDefinition {
	if m != nil {
		return m.VariableDefinitions
	}
	return nil
}

type Selection struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments            map[string]*Value   `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Directives           []*Directive        `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
	SelectionSet         []*Selection        `protobuf:"bytes,4,rep,name=selectionSet,proto3" json:"selectionSet,omitempty"`
	Definition           *FragmentDefinition `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Selection) Reset()         { *m = Selection{} }
func (m *Selection) String() string { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()    {}
func (*Selection) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{11}
}
func (m *Selection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Selection.Unmarshal(m, b)
}
func (m *Selection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Selection.Marshal(b, m, deterministic)
}
func (dst *Selection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Selection.Merge(dst, src)
}
func (m *Selection) XXX_Size() int {
	return xxx_messageInfo_Selection.Size(m)
}
func (m *Selection) XXX_DiscardUnknown() {
	xxx_messageInfo_Selection.DiscardUnknown(m)
}

var xxx_messageInfo_Selection proto.InternalMessageInfo

func (m *Selection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Selection) GetArguments() map[string]*Value {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *Selection) GetDirectives() []*Directive {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *Selection) GetSelectionSet() []*Selection {
	if m != nil {
		return m.SelectionSet
	}
	return nil
}

func (m *Selection) GetDefinition() *FragmentDefinition {
	if m != nil {
		return m.Definition
	}
	return nil
}

type OperationDefinition struct {
	Operation            string                `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VariableDefinitions  []*VariableDefinition `protobuf:"bytes,3,rep,name=variableDefinitions,proto3" json:"variableDefinitions,omitempty"`
	Directives           []*Directive          `protobuf:"bytes,4,rep,name=directives,proto3" json:"directives,omitempty"`
	SelectionSet         []*Selection          `protobuf:"bytes,5,rep,name=selectionSet,proto3" json:"selectionSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OperationDefinition) Reset()         { *m = OperationDefinition{} }
func (m *OperationDefinition) String() string { return proto.CompactTextString(m) }
func (*OperationDefinition) ProtoMessage()    {}
func (*OperationDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{12}
}
func (m *OperationDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperationDefinition.Unmarshal(m, b)
}
func (m *OperationDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperationDefinition.Marshal(b, m, deterministic)
}
func (dst *OperationDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperationDefinition.Merge(dst, src)
}
func (m *OperationDefinition) XXX_Size() int {
	return xxx_messageInfo_OperationDefinition.Size(m)
}
func (m *OperationDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_OperationDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_OperationDefinition proto.InternalMessageInfo

func (m *OperationDefinition) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *OperationDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OperationDefinition) GetVariableDefinitions() []*VariableDefinition {
	if m != nil {
		return m.VariableDefinitions
	}
	return nil
}

func (m *OperationDefinition) GetDirectives() []*Directive {
	if m != nil {
		return m.Directives
	}
	return nil
}

func (m *OperationDefinition) GetSelectionSet() []*Selection {
	if m != nil {
		return m.SelectionSet
	}
	return nil
}

type FieldResolveInfo struct {
	FieldName            string               `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	Path                 *ResponsePath        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ReturnType           *TypeRef             `protobuf:"bytes,3,opt,name=returnType,proto3" json:"returnType,omitempty"`
	ParentType           *TypeRef             `protobuf:"bytes,4,opt,name=parentType,proto3" json:"parentType,omitempty"`
	Operation            *OperationDefinition `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	VariableValues       map[string]*Value    `protobuf:"bytes,6,rep,name=variableValues,proto3" json:"variableValues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FieldResolveInfo) Reset()         { *m = FieldResolveInfo{} }
func (m *FieldResolveInfo) String() string { return proto.CompactTextString(m) }
func (*FieldResolveInfo) ProtoMessage()    {}
func (*FieldResolveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{13}
}
func (m *FieldResolveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldResolveInfo.Unmarshal(m, b)
}
func (m *FieldResolveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldResolveInfo.Marshal(b, m, deterministic)
}
func (dst *FieldResolveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldResolveInfo.Merge(dst, src)
}
func (m *FieldResolveInfo) XXX_Size() int {
	return xxx_messageInfo_FieldResolveInfo.Size(m)
}
func (m *FieldResolveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldResolveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FieldResolveInfo proto.InternalMessageInfo

func (m *FieldResolveInfo) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *FieldResolveInfo) GetPath() *ResponsePath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FieldResolveInfo) GetReturnType() *TypeRef {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

func (m *FieldResolveInfo) GetParentType() *TypeRef {
	if m != nil {
		return m.ParentType
	}
	return nil
}

func (m *FieldResolveInfo) GetOperation() *OperationDefinition {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *FieldResolveInfo) GetVariableValues() map[string]*Value {
	if m != nil {
		return m.VariableValues
	}
	return nil
}

type FieldResolveRequest struct {
	Function             *Function         `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Source               *Value            `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Arguments            map[string]*Value `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Info                 *FieldResolveInfo `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,5,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Protocol             *Value            `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FieldResolveRequest) Reset()         { *m = FieldResolveRequest{} }
func (m *FieldResolveRequest) String() string { return proto.CompactTextString(m) }
func (*FieldResolveRequest) ProtoMessage()    {}
func (*FieldResolveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{14}
}
func (m *FieldResolveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldResolveRequest.Unmarshal(m, b)
}
func (m *FieldResolveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldResolveRequest.Marshal(b, m, deterministic)
}
func (dst *FieldResolveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldResolveRequest.Merge(dst, src)
}
func (m *FieldResolveRequest) XXX_Size() int {
	return xxx_messageInfo_FieldResolveRequest.Size(m)
}
func (m *FieldResolveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldResolveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FieldResolveRequest proto.InternalMessageInfo

func (m *FieldResolveRequest) GetFunction() *Function {
	if m != nil {
		return m.Function
	}
	return nil
}

func (m *FieldResolveRequest) GetSource() *Value {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *FieldResolveRequest) GetArguments() map[string]*Value {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *FieldResolveRequest) GetInfo() *FieldResolveInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *FieldResolveRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *FieldResolveRequest) GetProtocol() *Value {
	if m != nil {
		return m.Protocol
	}
	return nil
}

type FieldResolveResponse struct {
	Response             *Value   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldResolveResponse) Reset()         { *m = FieldResolveResponse{} }
func (m *FieldResolveResponse) String() string { return proto.CompactTextString(m) }
func (*FieldResolveResponse) ProtoMessage()    {}
func (*FieldResolveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{15}
}
func (m *FieldResolveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldResolveResponse.Unmarshal(m, b)
}
func (m *FieldResolveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldResolveResponse.Marshal(b, m, deterministic)
}
func (dst *FieldResolveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldResolveResponse.Merge(dst, src)
}
func (m *FieldResolveResponse) XXX_Size() int {
	return xxx_messageInfo_FieldResolveResponse.Size(m)
}
func (m *FieldResolveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldResolveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FieldResolveResponse proto.InternalMessageInfo

func (m *FieldResolveResponse) GetResponse() *Value {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *FieldResolveResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type InterfaceResolveTypeInfo struct {
	FieldName            string               `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	Path                 *ResponsePath        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ReturnType           *TypeRef             `protobuf:"bytes,3,opt,name=returnType,proto3" json:"returnType,omitempty"`
	ParentType           *TypeRef             `protobuf:"bytes,4,opt,name=parentType,proto3" json:"parentType,omitempty"`
	Operation            *OperationDefinition `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	VariableValues       map[string]*Value    `protobuf:"bytes,6,rep,name=variableValues,proto3" json:"variableValues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InterfaceResolveTypeInfo) Reset()         { *m = InterfaceResolveTypeInfo{} }
func (m *InterfaceResolveTypeInfo) String() string { return proto.CompactTextString(m) }
func (*InterfaceResolveTypeInfo) ProtoMessage()    {}
func (*InterfaceResolveTypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{16}
}
func (m *InterfaceResolveTypeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceResolveTypeInfo.Unmarshal(m, b)
}
func (m *InterfaceResolveTypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceResolveTypeInfo.Marshal(b, m, deterministic)
}
func (dst *InterfaceResolveTypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceResolveTypeInfo.Merge(dst, src)
}
func (m *InterfaceResolveTypeInfo) XXX_Size() int {
	return xxx_messageInfo_InterfaceResolveTypeInfo.Size(m)
}
func (m *InterfaceResolveTypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceResolveTypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceResolveTypeInfo proto.InternalMessageInfo

func (m *InterfaceResolveTypeInfo) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *InterfaceResolveTypeInfo) GetPath() *ResponsePath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *InterfaceResolveTypeInfo) GetReturnType() *TypeRef {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

func (m *InterfaceResolveTypeInfo) GetParentType() *TypeRef {
	if m != nil {
		return m.ParentType
	}
	return nil
}

func (m *InterfaceResolveTypeInfo) GetOperation() *OperationDefinition {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *InterfaceResolveTypeInfo) GetVariableValues() map[string]*Value {
	if m != nil {
		return m.VariableValues
	}
	return nil
}

type InterfaceResolveTypeRequest struct {
	Function             *Function                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Value                *Value                    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Info                 *InterfaceResolveTypeInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *InterfaceResolveTypeRequest) Reset()         { *m = InterfaceResolveTypeRequest{} }
func (m *InterfaceResolveTypeRequest) String() string { return proto.CompactTextString(m) }
func (*InterfaceResolveTypeRequest) ProtoMessage()    {}
func (*InterfaceResolveTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{17}
}
func (m *InterfaceResolveTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceResolveTypeRequest.Unmarshal(m, b)
}
func (m *InterfaceResolveTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceResolveTypeRequest.Marshal(b, m, deterministic)
}
func (dst *InterfaceResolveTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceResolveTypeRequest.Merge(dst, src)
}
func (m *InterfaceResolveTypeRequest) XXX_Size() int {
	return xxx_messageInfo_InterfaceResolveTypeRequest.Size(m)
}
func (m *InterfaceResolveTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceResolveTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceResolveTypeRequest proto.InternalMessageInfo

func (m *InterfaceResolveTypeRequest) GetFunction() *Function {
	if m != nil {
		return m.Function
	}
	return nil
}

func (m *InterfaceResolveTypeRequest) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *InterfaceResolveTypeRequest) GetInfo() *InterfaceResolveTypeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type InterfaceResolveTypeResponse struct {
	Type                 *TypeRef `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterfaceResolveTypeResponse) Reset()         { *m = InterfaceResolveTypeResponse{} }
func (m *InterfaceResolveTypeResponse) String() string { return proto.CompactTextString(m) }
func (*InterfaceResolveTypeResponse) ProtoMessage()    {}
func (*InterfaceResolveTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{18}
}
func (m *InterfaceResolveTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterfaceResolveTypeResponse.Unmarshal(m, b)
}
func (m *InterfaceResolveTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterfaceResolveTypeResponse.Marshal(b, m, deterministic)
}
func (dst *InterfaceResolveTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterfaceResolveTypeResponse.Merge(dst, src)
}
func (m *InterfaceResolveTypeResponse) XXX_Size() int {
	return xxx_messageInfo_InterfaceResolveTypeResponse.Size(m)
}
func (m *InterfaceResolveTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InterfaceResolveTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InterfaceResolveTypeResponse proto.InternalMessageInfo

func (m *InterfaceResolveTypeResponse) GetType() *TypeRef {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *InterfaceResolveTypeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ScalarParseRequest struct {
	Value                *Value    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Function             *Function `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScalarParseRequest) Reset()         { *m = ScalarParseRequest{} }
func (m *ScalarParseRequest) String() string { return proto.CompactTextString(m) }
func (*ScalarParseRequest) ProtoMessage()    {}
func (*ScalarParseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{19}
}
func (m *ScalarParseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarParseRequest.Unmarshal(m, b)
}
func (m *ScalarParseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarParseRequest.Marshal(b, m, deterministic)
}
func (dst *ScalarParseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarParseRequest.Merge(dst, src)
}
func (m *ScalarParseRequest) XXX_Size() int {
	return xxx_messageInfo_ScalarParseRequest.Size(m)
}
func (m *ScalarParseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarParseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarParseRequest proto.InternalMessageInfo

func (m *ScalarParseRequest) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ScalarParseRequest) GetFunction() *Function {
	if m != nil {
		return m.Function
	}
	return nil
}

type ScalarParseResponse struct {
	Value                *Value   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScalarParseResponse) Reset()         { *m = ScalarParseResponse{} }
func (m *ScalarParseResponse) String() string { return proto.CompactTextString(m) }
func (*ScalarParseResponse) ProtoMessage()    {}
func (*ScalarParseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{20}
}
func (m *ScalarParseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarParseResponse.Unmarshal(m, b)
}
func (m *ScalarParseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarParseResponse.Marshal(b, m, deterministic)
}
func (dst *ScalarParseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarParseResponse.Merge(dst, src)
}
func (m *ScalarParseResponse) XXX_Size() int {
	return xxx_messageInfo_ScalarParseResponse.Size(m)
}
func (m *ScalarParseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarParseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarParseResponse proto.InternalMessageInfo

func (m *ScalarParseResponse) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ScalarParseResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ScalarSerializeRequest struct {
	Value                *Value    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Function             *Function `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScalarSerializeRequest) Reset()         { *m = ScalarSerializeRequest{} }
func (m *ScalarSerializeRequest) String() string { return proto.CompactTextString(m) }
func (*ScalarSerializeRequest) ProtoMessage()    {}
func (*ScalarSerializeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{21}
}
func (m *ScalarSerializeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarSerializeRequest.Unmarshal(m, b)
}
func (m *ScalarSerializeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarSerializeRequest.Marshal(b, m, deterministic)
}
func (dst *ScalarSerializeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarSerializeRequest.Merge(dst, src)
}
func (m *ScalarSerializeRequest) XXX_Size() int {
	return xxx_messageInfo_ScalarSerializeRequest.Size(m)
}
func (m *ScalarSerializeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarSerializeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarSerializeRequest proto.InternalMessageInfo

func (m *ScalarSerializeRequest) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ScalarSerializeRequest) GetFunction() *Function {
	if m != nil {
		return m.Function
	}
	return nil
}

type ScalarSerializeResponse struct {
	Value                *Value   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScalarSerializeResponse) Reset()         { *m = ScalarSerializeResponse{} }
func (m *ScalarSerializeResponse) String() string { return proto.CompactTextString(m) }
func (*ScalarSerializeResponse) ProtoMessage()    {}
func (*ScalarSerializeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{22}
}
func (m *ScalarSerializeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScalarSerializeResponse.Unmarshal(m, b)
}
func (m *ScalarSerializeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScalarSerializeResponse.Marshal(b, m, deterministic)
}
func (dst *ScalarSerializeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScalarSerializeResponse.Merge(dst, src)
}
func (m *ScalarSerializeResponse) XXX_Size() int {
	return xxx_messageInfo_ScalarSerializeResponse.Size(m)
}
func (m *ScalarSerializeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScalarSerializeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScalarSerializeResponse proto.InternalMessageInfo

func (m *ScalarSerializeResponse) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ScalarSerializeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UnionResolveTypeInfo struct {
	FieldName            string               `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	Path                 *ResponsePath        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ReturnType           *TypeRef             `protobuf:"bytes,3,opt,name=returnType,proto3" json:"returnType,omitempty"`
	ParentType           *TypeRef             `protobuf:"bytes,4,opt,name=parentType,proto3" json:"parentType,omitempty"`
	Operation            *OperationDefinition `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	VariableValues       map[string]*Value    `protobuf:"bytes,6,rep,name=variableValues,proto3" json:"variableValues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UnionResolveTypeInfo) Reset()         { *m = UnionResolveTypeInfo{} }
func (m *UnionResolveTypeInfo) String() string { return proto.CompactTextString(m) }
func (*UnionResolveTypeInfo) ProtoMessage()    {}
func (*UnionResolveTypeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{23}
}
func (m *UnionResolveTypeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnionResolveTypeInfo.Unmarshal(m, b)
}
func (m *UnionResolveTypeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnionResolveTypeInfo.Marshal(b, m, deterministic)
}
func (dst *UnionResolveTypeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnionResolveTypeInfo.Merge(dst, src)
}
func (m *UnionResolveTypeInfo) XXX_Size() int {
	return xxx_messageInfo_UnionResolveTypeInfo.Size(m)
}
func (m *UnionResolveTypeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UnionResolveTypeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UnionResolveTypeInfo proto.InternalMessageInfo

func (m *UnionResolveTypeInfo) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *UnionResolveTypeInfo) GetPath() *ResponsePath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *UnionResolveTypeInfo) GetReturnType() *TypeRef {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

func (m *UnionResolveTypeInfo) GetParentType() *TypeRef {
	if m != nil {
		return m.ParentType
	}
	return nil
}

func (m *UnionResolveTypeInfo) GetOperation() *OperationDefinition {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *UnionResolveTypeInfo) GetVariableValues() map[string]*Value {
	if m != nil {
		return m.VariableValues
	}
	return nil
}

type UnionResolveTypeRequest struct {
	Function             *Function             `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Value                *Value                `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Info                 *UnionResolveTypeInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UnionResolveTypeRequest) Reset()         { *m = UnionResolveTypeRequest{} }
func (m *UnionResolveTypeRequest) String() string { return proto.CompactTextString(m) }
func (*UnionResolveTypeRequest) ProtoMessage()    {}
func (*UnionResolveTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{24}
}
func (m *UnionResolveTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnionResolveTypeRequest.Unmarshal(m, b)
}
func (m *UnionResolveTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnionResolveTypeRequest.Marshal(b, m, deterministic)
}
func (dst *UnionResolveTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnionResolveTypeRequest.Merge(dst, src)
}
func (m *UnionResolveTypeRequest) XXX_Size() int {
	return xxx_messageInfo_UnionResolveTypeRequest.Size(m)
}
func (m *UnionResolveTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnionResolveTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnionResolveTypeRequest proto.InternalMessageInfo

func (m *UnionResolveTypeRequest) GetFunction() *Function {
	if m != nil {
		return m.Function
	}
	return nil
}

func (m *UnionResolveTypeRequest) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UnionResolveTypeRequest) GetInfo() *UnionResolveTypeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type UnionResolveTypeResponse struct {
	Type                 *TypeRef `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnionResolveTypeResponse) Reset()         { *m = UnionResolveTypeResponse{} }
func (m *UnionResolveTypeResponse) String() string { return proto.CompactTextString(m) }
func (*UnionResolveTypeResponse) ProtoMessage()    {}
func (*UnionResolveTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{25}
}
func (m *UnionResolveTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnionResolveTypeResponse.Unmarshal(m, b)
}
func (m *UnionResolveTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnionResolveTypeResponse.Marshal(b, m, deterministic)
}
func (dst *UnionResolveTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnionResolveTypeResponse.Merge(dst, src)
}
func (m *UnionResolveTypeResponse) XXX_Size() int {
	return xxx_messageInfo_UnionResolveTypeResponse.Size(m)
}
func (m *UnionResolveTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnionResolveTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnionResolveTypeResponse proto.InternalMessageInfo

func (m *UnionResolveTypeResponse) GetType() *TypeRef {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *UnionResolveTypeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type StreamInfo struct {
	FieldName            string               `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	Path                 *ResponsePath        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ReturnType           *TypeRef             `protobuf:"bytes,3,opt,name=returnType,proto3" json:"returnType,omitempty"`
	ParentType           *TypeRef             `protobuf:"bytes,4,opt,name=parentType,proto3" json:"parentType,omitempty"`
	Operation            *OperationDefinition `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	VariableValues       map[string]*Value    `protobuf:"bytes,6,rep,name=variableValues,proto3" json:"variableValues,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StreamInfo) Reset()         { *m = StreamInfo{} }
func (m *StreamInfo) String() string { return proto.CompactTextString(m) }
func (*StreamInfo) ProtoMessage()    {}
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{26}
}
func (m *StreamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamInfo.Unmarshal(m, b)
}
func (m *StreamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamInfo.Marshal(b, m, deterministic)
}
func (dst *StreamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamInfo.Merge(dst, src)
}
func (m *StreamInfo) XXX_Size() int {
	return xxx_messageInfo_StreamInfo.Size(m)
}
func (m *StreamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StreamInfo proto.InternalMessageInfo

func (m *StreamInfo) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *StreamInfo) GetPath() *ResponsePath {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *StreamInfo) GetReturnType() *TypeRef {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

func (m *StreamInfo) GetParentType() *TypeRef {
	if m != nil {
		return m.ParentType
	}
	return nil
}

func (m *StreamInfo) GetOperation() *OperationDefinition {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (m *StreamInfo) GetVariableValues() map[string]*Value {
	if m != nil {
		return m.VariableValues
	}
	return nil
}

type StreamRequest struct {
	Function             *Function         `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Arguments            map[string]*Value `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Info                 *StreamInfo       `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Secrets              map[string]string `protobuf:"bytes,4,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Protocol             *Value            `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{27}
}
func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (dst *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(dst, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetFunction() *Function {
	if m != nil {
		return m.Function
	}
	return nil
}

func (m *StreamRequest) GetArguments() map[string]*Value {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *StreamRequest) GetInfo() *StreamInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *StreamRequest) GetSecrets() map[string]string {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *StreamRequest) GetProtocol() *Value {
	if m != nil {
		return m.Protocol
	}
	return nil
}

type StreamMessage struct {
	Response             *Value   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMessage) Reset()         { *m = StreamMessage{} }
func (m *StreamMessage) String() string { return proto.CompactTextString(m) }
func (*StreamMessage) ProtoMessage()    {}
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{28}
}
func (m *StreamMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMessage.Unmarshal(m, b)
}
func (m *StreamMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMessage.Marshal(b, m, deterministic)
}
func (dst *StreamMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMessage.Merge(dst, src)
}
func (m *StreamMessage) XXX_Size() int {
	return xxx_messageInfo_StreamMessage.Size(m)
}
func (m *StreamMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMessage proto.InternalMessageInfo

func (m *StreamMessage) GetResponse() *Value {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *StreamMessage) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ByteStreamRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByteStreamRequest) Reset()         { *m = ByteStreamRequest{} }
func (m *ByteStreamRequest) String() string { return proto.CompactTextString(m) }
func (*ByteStreamRequest) ProtoMessage()    {}
func (*ByteStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{29}
}
func (m *ByteStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteStreamRequest.Unmarshal(m, b)
}
func (m *ByteStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteStreamRequest.Marshal(b, m, deterministic)
}
func (dst *ByteStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteStreamRequest.Merge(dst, src)
}
func (m *ByteStreamRequest) XXX_Size() int {
	return xxx_messageInfo_ByteStreamRequest.Size(m)
}
func (m *ByteStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ByteStreamRequest proto.InternalMessageInfo

type ByteStream struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByteStream) Reset()         { *m = ByteStream{} }
func (m *ByteStream) String() string { return proto.CompactTextString(m) }
func (*ByteStream) ProtoMessage()    {}
func (*ByteStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_driver_adbc89d145461bcd, []int{30}
}
func (m *ByteStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteStream.Unmarshal(m, b)
}
func (m *ByteStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteStream.Marshal(b, m, deterministic)
}
func (dst *ByteStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteStream.Merge(dst, src)
}
func (m *ByteStream) XXX_Size() int {
	return xxx_messageInfo_ByteStream.Size(m)
}
func (m *ByteStream) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteStream.DiscardUnknown(m)
}

var xxx_messageInfo_ByteStream proto.InternalMessageInfo

func (m *ByteStream) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ObjectValue)(nil), "proto.ObjectValue")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.ObjectValue.PropsEntry")
	proto.RegisterType((*ArrayValue)(nil), "proto.ArrayValue")
	proto.RegisterType((*Value)(nil), "proto.Value")
	proto.RegisterType((*Error)(nil), "proto.Error")
	proto.RegisterType((*Function)(nil), "proto.Function")
	proto.RegisterType((*TypeRef)(nil), "proto.TypeRef")
	proto.RegisterType((*ResponsePath)(nil), "proto.ResponsePath")
	proto.RegisterType((*Variable)(nil), "proto.Variable")
	proto.RegisterType((*VariableDefinition)(nil), "proto.VariableDefinition")
	proto.RegisterType((*Directive)(nil), "proto.Directive")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.Directive.ArgumentsEntry")
	proto.RegisterType((*FragmentDefinition)(nil), "proto.FragmentDefinition")
	proto.RegisterType((*Selection)(nil), "proto.Selection")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.Selection.ArgumentsEntry")
	proto.RegisterType((*OperationDefinition)(nil), "proto.OperationDefinition")
	proto.RegisterType((*FieldResolveInfo)(nil), "proto.FieldResolveInfo")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.FieldResolveInfo.VariableValuesEntry")
	proto.RegisterType((*FieldResolveRequest)(nil), "proto.FieldResolveRequest")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.FieldResolveRequest.ArgumentsEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.FieldResolveRequest.SecretsEntry")
	proto.RegisterType((*FieldResolveResponse)(nil), "proto.FieldResolveResponse")
	proto.RegisterType((*InterfaceResolveTypeInfo)(nil), "proto.InterfaceResolveTypeInfo")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.InterfaceResolveTypeInfo.VariableValuesEntry")
	proto.RegisterType((*InterfaceResolveTypeRequest)(nil), "proto.InterfaceResolveTypeRequest")
	proto.RegisterType((*InterfaceResolveTypeResponse)(nil), "proto.InterfaceResolveTypeResponse")
	proto.RegisterType((*ScalarParseRequest)(nil), "proto.ScalarParseRequest")
	proto.RegisterType((*ScalarParseResponse)(nil), "proto.ScalarParseResponse")
	proto.RegisterType((*ScalarSerializeRequest)(nil), "proto.ScalarSerializeRequest")
	proto.RegisterType((*ScalarSerializeResponse)(nil), "proto.ScalarSerializeResponse")
	proto.RegisterType((*UnionResolveTypeInfo)(nil), "proto.UnionResolveTypeInfo")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.UnionResolveTypeInfo.VariableValuesEntry")
	proto.RegisterType((*UnionResolveTypeRequest)(nil), "proto.UnionResolveTypeRequest")
	proto.RegisterType((*UnionResolveTypeResponse)(nil), "proto.UnionResolveTypeResponse")
	proto.RegisterType((*StreamInfo)(nil), "proto.StreamInfo")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.StreamInfo.VariableValuesEntry")
	proto.RegisterType((*StreamRequest)(nil), "proto.StreamRequest")
	proto.RegisterMapType((map[string]*Value)(nil), "proto.StreamRequest.ArgumentsEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.StreamRequest.SecretsEntry")
	proto.RegisterType((*StreamMessage)(nil), "proto.StreamMessage")
	proto.RegisterType((*ByteStreamRequest)(nil), "proto.ByteStreamRequest")
	proto.RegisterType((*ByteStream)(nil), "proto.ByteStream")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DriverClient is the client API for Driver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DriverClient interface {
	FieldResolve(ctx context.Context, in *FieldResolveRequest, opts ...grpc.CallOption) (*FieldResolveResponse, error)
	InterfaceResolveType(ctx context.Context, in *InterfaceResolveTypeRequest, opts ...grpc.CallOption) (*InterfaceResolveTypeResponse, error)
	ScalarParse(ctx context.Context, in *ScalarParseRequest, opts ...grpc.CallOption) (*ScalarParseResponse, error)
	ScalarSerialize(ctx context.Context, in *ScalarSerializeRequest, opts ...grpc.CallOption) (*ScalarSerializeResponse, error)
	UnionResolveType(ctx context.Context, in *UnionResolveTypeRequest, opts ...grpc.CallOption) (*UnionResolveTypeResponse, error)
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Driver_StreamClient, error)
	Stdout(ctx context.Context, in *ByteStreamRequest, opts ...grpc.CallOption) (Driver_StdoutClient, error)
	Stderr(ctx context.Context, in *ByteStreamRequest, opts ...grpc.CallOption) (Driver_StderrClient, error)
}

type driverClient struct {
	cc *grpc.ClientConn
}

func NewDriverClient(cc *grpc.ClientConn) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) FieldResolve(ctx context.Context, in *FieldResolveRequest, opts ...grpc.CallOption) (*FieldResolveResponse, error) {
	out := new(FieldResolveResponse)
	err := c.cc.Invoke(ctx, "/proto.Driver/FieldResolve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) InterfaceResolveType(ctx context.Context, in *InterfaceResolveTypeRequest, opts ...grpc.CallOption) (*InterfaceResolveTypeResponse, error) {
	out := new(InterfaceResolveTypeResponse)
	err := c.cc.Invoke(ctx, "/proto.Driver/InterfaceResolveType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) ScalarParse(ctx context.Context, in *ScalarParseRequest, opts ...grpc.CallOption) (*ScalarParseResponse, error) {
	out := new(ScalarParseResponse)
	err := c.cc.Invoke(ctx, "/proto.Driver/ScalarParse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) ScalarSerialize(ctx context.Context, in *ScalarSerializeRequest, opts ...grpc.CallOption) (*ScalarSerializeResponse, error) {
	out := new(ScalarSerializeResponse)
	err := c.cc.Invoke(ctx, "/proto.Driver/ScalarSerialize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) UnionResolveType(ctx context.Context, in *UnionResolveTypeRequest, opts ...grpc.CallOption) (*UnionResolveTypeResponse, error) {
	out := new(UnionResolveTypeResponse)
	err := c.cc.Invoke(ctx, "/proto.Driver/UnionResolveType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Driver_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Driver_serviceDesc.Streams[0], "/proto.Driver/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Driver_StreamClient interface {
	Recv() (*StreamMessage, error)
	grpc.ClientStream
}

type driverStreamClient struct {
	grpc.ClientStream
}

func (x *driverStreamClient) Recv() (*StreamMessage, error) {
	m := new(StreamMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driverClient) Stdout(ctx context.Context, in *ByteStreamRequest, opts ...grpc.CallOption) (Driver_StdoutClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Driver_serviceDesc.Streams[1], "/proto.Driver/Stdout", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverStdoutClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Driver_StdoutClient interface {
	Recv() (*ByteStream, error)
	grpc.ClientStream
}

type driverStdoutClient struct {
	grpc.ClientStream
}

func (x *driverStdoutClient) Recv() (*ByteStream, error) {
	m := new(ByteStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *driverClient) Stderr(ctx context.Context, in *ByteStreamRequest, opts ...grpc.CallOption) (Driver_StderrClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Driver_serviceDesc.Streams[2], "/proto.Driver/Stderr", opts...)
	if err != nil {
		return nil, err
	}
	x := &driverStderrClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Driver_StderrClient interface {
	Recv() (*ByteStream, error)
	grpc.ClientStream
}

type driverStderrClient struct {
	grpc.ClientStream
}

func (x *driverStderrClient) Recv() (*ByteStream, error) {
	m := new(ByteStream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DriverServer is the server API for Driver service.
type DriverServer interface {
	FieldResolve(context.Context, *FieldResolveRequest) (*FieldResolveResponse, error)
	InterfaceResolveType(context.Context, *InterfaceResolveTypeRequest) (*InterfaceResolveTypeResponse, error)
	ScalarParse(context.Context, *ScalarParseRequest) (*ScalarParseResponse, error)
	ScalarSerialize(context.Context, *ScalarSerializeRequest) (*ScalarSerializeResponse, error)
	UnionResolveType(context.Context, *UnionResolveTypeRequest) (*UnionResolveTypeResponse, error)
	Stream(*StreamRequest, Driver_StreamServer) error
	Stdout(*ByteStreamRequest, Driver_StdoutServer) error
	Stderr(*ByteStreamRequest, Driver_StderrServer) error
}

func RegisterDriverServer(s *grpc.Server, srv DriverServer) {
	s.RegisterService(&_Driver_serviceDesc, srv)
}

func _Driver_FieldResolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FieldResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).FieldResolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Driver/FieldResolve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).FieldResolve(ctx, req.(*FieldResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_InterfaceResolveType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterfaceResolveTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).InterfaceResolveType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Driver/InterfaceResolveType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).InterfaceResolveType(ctx, req.(*InterfaceResolveTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_ScalarParse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScalarParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).ScalarParse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Driver/ScalarParse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).ScalarParse(ctx, req.(*ScalarParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_ScalarSerialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScalarSerializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).ScalarSerialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Driver/ScalarSerialize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).ScalarSerialize(ctx, req.(*ScalarSerializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_UnionResolveType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnionResolveTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).UnionResolveType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Driver/UnionResolveType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).UnionResolveType(ctx, req.(*UnionResolveTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).Stream(m, &driverStreamServer{stream})
}

type Driver_StreamServer interface {
	Send(*StreamMessage) error
	grpc.ServerStream
}

type driverStreamServer struct {
	grpc.ServerStream
}

func (x *driverStreamServer) Send(m *StreamMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Driver_Stdout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ByteStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).Stdout(m, &driverStdoutServer{stream})
}

type Driver_StdoutServer interface {
	Send(*ByteStream) error
	grpc.ServerStream
}

type driverStdoutServer struct {
	grpc.ServerStream
}

func (x *driverStdoutServer) Send(m *ByteStream) error {
	return x.ServerStream.SendMsg(m)
}

func _Driver_Stderr_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ByteStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DriverServer).Stderr(m, &driverStderrServer{stream})
}

type Driver_StderrServer interface {
	Send(*ByteStream) error
	grpc.ServerStream
}

type driverStderrServer struct {
	grpc.ServerStream
}

func (x *driverStderrServer) Send(m *ByteStream) error {
	return x.ServerStream.SendMsg(m)
}

var _Driver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FieldResolve",
			Handler:    _Driver_FieldResolve_Handler,
		},
		{
			MethodName: "InterfaceResolveType",
			Handler:    _Driver_InterfaceResolveType_Handler,
		},
		{
			MethodName: "ScalarParse",
			Handler:    _Driver_ScalarParse_Handler,
		},
		{
			MethodName: "ScalarSerialize",
			Handler:    _Driver_ScalarSerialize_Handler,
		},
		{
			MethodName: "UnionResolveType",
			Handler:    _Driver_UnionResolveType_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Driver_Stream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stdout",
			Handler:       _Driver_Stdout_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stderr",
			Handler:       _Driver_Stderr_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "driver.proto",
}

func init() { proto.RegisterFile("driver.proto", fileDescriptor_driver_adbc89d145461bcd) }

var fileDescriptor_driver_adbc89d145461bcd = []byte{
	// 1379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0x7a, 0x6d, 0x27, 0x7e, 0x71, 0xd3, 0x64, 0x6c, 0xd1, 0xed, 0xb6, 0x4d, 0xdd, 0x6d,
	0xab, 0x1a, 0x22, 0xa5, 0x51, 0x52, 0x41, 0x29, 0xe2, 0x90, 0x90, 0xa6, 0x29, 0xa8, 0x4d, 0xb4,
	0x86, 0xf6, 0x80, 0xaa, 0x6a, 0x6c, 0xcf, 0xa6, 0x0b, 0xeb, 0x5d, 0x33, 0xbb, 0xb6, 0x64, 0x6e,
	0x5c, 0x91, 0x38, 0x72, 0x40, 0x9c, 0x10, 0x27, 0xf8, 0x4f, 0x38, 0x70, 0xe2, 0x3f, 0xe1, 0x8c,
	0x04, 0x9a, 0xd9, 0xd9, 0xef, 0x5d, 0xc7, 0x4d, 0x53, 0x45, 0x28, 0xa7, 0x78, 0xe7, 0xfd, 0xde,
	0xc7, 0xfc, 0xde, 0xc7, 0xbe, 0x0d, 0xd4, 0xfb, 0xd4, 0x1c, 0x13, 0xba, 0x3e, 0xa4, 0x8e, 0xe7,
	0xa0, 0x0a, 0xff, 0xa3, 0x7d, 0x2f, 0xc1, 0xe2, 0x41, 0xf7, 0x2b, 0xd2, 0xf3, 0x9e, 0x61, 0x6b,
	0x44, 0xd0, 0x16, 0x30, 0xc1, 0xd0, 0x55, 0xa4, 0x96, 0xdc, 0x5e, 0xdc, 0xbc, 0xe6, 0xa3, 0xd7,
	0x63, 0x90, 0xf5, 0x43, 0x26, 0x7f, 0x68, 0x7b, 0x74, 0xa2, 0xfb, 0x58, 0x75, 0x0f, 0x20, 0x3a,
	0x44, 0xcb, 0x20, 0x7f, 0x4d, 0x26, 0x8a, 0xd4, 0x92, 0xda, 0x35, 0x9d, 0xfd, 0x44, 0x1a, 0x54,
	0xc6, 0x4c, 0x55, 0x29, 0xb5, 0xa4, 0xf6, 0xe2, 0x66, 0x5d, 0x18, 0xe5, 0xe6, 0x74, 0x5f, 0xf4,
	0xa0, 0x74, 0x5f, 0xd2, 0x36, 0x00, 0xb6, 0x29, 0xc5, 0x13, 0x3f, 0x14, 0x0d, 0x2a, 0xa6, 0x47,
	0x06, 0x41, 0x28, 0x29, 0x2d, 0x2e, 0xd2, 0xfe, 0x96, 0xa0, 0xe2, 0xa3, 0x97, 0x40, 0x32, 0xb9,
	0x4f, 0x79, 0x7f, 0x4e, 0x97, 0x4c, 0xf6, 0x3c, 0xe2, 0xfe, 0xca, 0xec, 0x79, 0xc4, 0x9e, 0x0d,
	0x45, 0x6e, 0x49, 0x6d, 0x89, 0x3d, 0x1b, 0xec, 0xd9, 0x55, 0xca, 0x2c, 0x46, 0xf6, 0xec, 0xb2,
	0xe7, 0xae, 0x52, 0x69, 0x49, 0xed, 0x05, 0xf6, 0xdc, 0x45, 0x1a, 0x48, 0x8e, 0x52, 0xe5, 0xf1,
	0xa2, 0x2c, 0x09, 0x0c, 0xe3, 0xa0, 0x1b, 0x20, 0x61, 0x65, 0x9e, 0x63, 0x56, 0x04, 0x26, 0x8a,
	0x9f, 0x41, 0x30, 0x42, 0x20, 0x63, 0x7b, 0xa2, 0x2c, 0xb4, 0xa4, 0x76, 0x7d, 0x7f, 0x4e, 0x67,
	0x0f, 0xe8, 0x2a, 0x2c, 0x8c, 0x31, 0x35, 0x71, 0xd7, 0x22, 0x4a, 0x4d, 0x44, 0x10, 0x9e, 0x30,
	0x0d, 0xdb, 0xb4, 0x14, 0x10, 0xa1, 0xb0, 0x87, 0x9d, 0x3a, 0x80, 0x47, 0x5c, 0xef, 0x25, 0xa7,
	0x4a, 0xbb, 0x0c, 0x95, 0x87, 0x94, 0x3a, 0x94, 0x31, 0x3d, 0x70, 0x8f, 0x02, 0xa6, 0x07, 0xee,
	0x91, 0xb6, 0x0a, 0x0b, 0x7b, 0x23, 0xbb, 0xe7, 0x99, 0x8e, 0x8d, 0x10, 0x94, 0x6d, 0x3c, 0x20,
	0x42, 0xcc, 0x7f, 0x6b, 0xdf, 0x49, 0x30, 0xff, 0xf9, 0x64, 0x48, 0x74, 0x62, 0xa0, 0x66, 0x5c,
	0xbe, 0x3f, 0xe7, 0x23, 0xd0, 0x7b, 0x30, 0x6f, 0x3b, 0xf6, 0xd3, 0x91, 0x65, 0x89, 0x6c, 0x2d,
	0x89, 0x9b, 0x09, 0xb5, 0xfd, 0x39, 0x3d, 0x00, 0xa0, 0x5b, 0x50, 0xb6, 0x4c, 0xd7, 0xe3, 0xb4,
	0xe6, 0x01, 0xb9, 0x74, 0x67, 0x09, 0xea, 0x3c, 0x78, 0x6f, 0x32, 0x24, 0x94, 0x18, 0xda, 0x73,
	0xa8, 0xeb, 0xc4, 0x1d, 0x3a, 0xb6, 0x4b, 0x0e, 0xb1, 0xf7, 0x0a, 0xad, 0x46, 0xf5, 0x92, 0xce,
	0x32, 0xaf, 0x9e, 0x3b, 0x50, 0x1e, 0x52, 0x32, 0x16, 0xe1, 0x34, 0x04, 0x20, 0x6e, 0x42, 0xe7,
	0x00, 0x76, 0xf9, 0x67, 0x11, 0x8b, 0xd9, 0xcb, 0xbb, 0x80, 0x02, 0xf9, 0x2e, 0x31, 0x4c, 0xdb,
	0xe4, 0x34, 0xad, 0xc5, 0xb2, 0xe1, 0xc7, 0x70, 0x31, 0x8c, 0xc1, 0x3f, 0x8e, 0x25, 0x67, 0x03,
	0xea, 0x7d, 0x62, 0xe0, 0x91, 0xe5, 0x97, 0x41, 0x6e, 0x41, 0x27, 0x10, 0xda, 0xef, 0x12, 0xd4,
	0x76, 0x4d, 0x4a, 0x7a, 0x9e, 0x39, 0xce, 0x0d, 0x0b, 0x7d, 0x0c, 0x35, 0x4c, 0x8f, 0x46, 0x03,
	0x62, 0x7b, 0xae, 0x52, 0xe2, 0xb5, 0x7e, 0x5d, 0x18, 0x0c, 0x15, 0xd7, 0xb7, 0x03, 0x84, 0xdf,
	0x78, 0x91, 0x86, 0xfa, 0x29, 0x2c, 0x25, 0x85, 0x6f, 0xd0, 0x80, 0xff, 0x4a, 0x80, 0xf6, 0x28,
	0x3e, 0x62, 0xc6, 0x62, 0x14, 0x6d, 0x00, 0xf4, 0x83, 0x48, 0x82, 0x76, 0x5c, 0x4e, 0x87, 0xa8,
	0xc7, 0x30, 0xe8, 0x1e, 0x5c, 0x60, 0xe9, 0xfe, 0xc4, 0xb1, 0xfb, 0xdc, 0x44, 0x7e, 0x2d, 0xe9,
	0x49, 0x10, 0xba, 0x07, 0x75, 0x97, 0x58, 0x84, 0x97, 0x6f, 0x87, 0xb0, 0xba, 0x8a, 0x7b, 0xea,
	0x04, 0x22, 0x3d, 0x81, 0x42, 0x9f, 0x41, 0x63, 0x9c, 0x49, 0x2b, 0xeb, 0x6d, 0xa6, 0x7c, 0x39,
	0x95, 0xcb, 0x08, 0xa1, 0xe7, 0x69, 0x69, 0x7f, 0x96, 0xa0, 0x16, 0x3a, 0x7a, 0xdd, 0x74, 0x85,
	0x8a, 0xc5, 0xe9, 0x4a, 0x71, 0x29, 0xcf, 0xc4, 0x65, 0x92, 0x95, 0xf2, 0x4c, 0xac, 0x7c, 0x08,
	0xd0, 0x0f, 0xef, 0xc5, 0x07, 0x5b, 0x44, 0x46, 0x36, 0xc5, 0x7a, 0x0c, 0x7c, 0xaa, 0x15, 0xf5,
	0x8f, 0x04, 0x8d, 0x83, 0x21, 0xa1, 0x98, 0x59, 0x8e, 0x95, 0xd4, 0x55, 0xa8, 0x39, 0xc1, 0xb1,
	0xb0, 0x1b, 0x1d, 0x84, 0xbc, 0x97, 0x62, 0xbc, 0x17, 0xa4, 0x59, 0x3e, 0x49, 0x9a, 0x53, 0x59,
	0x28, 0x9f, 0x20, 0x0b, 0x95, 0x59, 0xb2, 0xa0, 0xfd, 0x24, 0xc3, 0xf2, 0x9e, 0x49, 0xac, 0xbe,
	0x4e, 0x5c, 0xc7, 0x1a, 0x93, 0xc7, 0xb6, 0xe1, 0xb0, 0xbb, 0x1b, 0xec, 0xec, 0x69, 0x54, 0x5a,
	0xd1, 0x01, 0x1f, 0x77, 0xd8, 0x7b, 0x35, 0x7d, 0xdc, 0xb1, 0xb9, 0xb9, 0x0e, 0x40, 0x89, 0x37,
	0xa2, 0x36, 0xeb, 0xa6, 0xfc, 0x19, 0xac, 0xc7, 0x10, 0x0c, 0x3f, 0xc4, 0x94, 0xd8, 0x1e, 0xc7,
	0x97, 0xf3, 0xf1, 0x11, 0x02, 0xdd, 0x8f, 0xa7, 0xc8, 0x2f, 0x20, 0x35, 0x78, 0x13, 0x66, 0x33,
	0x1a, 0x4f, 0x5f, 0x07, 0x96, 0x02, 0xd2, 0x79, 0x41, 0xb8, 0x4a, 0x95, 0xb3, 0xb5, 0x16, 0xd4,
	0x5f, 0x8a, 0x91, 0x30, 0x6d, 0x3e, 0xda, 0xef, 0x99, 0x94, 0x09, 0xf5, 0x00, 0x1a, 0x39, 0xb0,
	0x37, 0x28, 0xcd, 0xbf, 0x64, 0x68, 0xc4, 0x23, 0xd1, 0xc9, 0x37, 0x23, 0xe2, 0x7a, 0xec, 0x85,
	0x60, 0x88, 0x77, 0x68, 0xea, 0x85, 0x10, 0xbc, 0x5a, 0xf5, 0x10, 0x80, 0x6e, 0x41, 0xd5, 0x75,
	0x46, 0xb4, 0x97, 0xef, 0x4d, 0xc8, 0xd0, 0xa3, 0xf8, 0xcc, 0xf0, 0x2b, 0xf6, 0xdd, 0x1c, 0x2e,
	0x44, 0x04, 0x53, 0xa6, 0xc7, 0x1a, 0x94, 0x4d, 0xdb, 0x70, 0x44, 0xf6, 0x2e, 0x15, 0xf0, 0xa9,
	0x73, 0x10, 0xda, 0x86, 0x79, 0x97, 0xf4, 0x28, 0xf1, 0x5c, 0x51, 0xad, 0x77, 0xa6, 0xf8, 0xec,
	0xf8, 0x48, 0xdf, 0x63, 0xa0, 0x87, 0xda, 0xb0, 0xc0, 0x55, 0x7a, 0x8e, 0x25, 0x96, 0xa1, 0xe4,
	0x05, 0x43, 0xe9, 0x69, 0x0e, 0x0d, 0xf5, 0x01, 0xd4, 0xe3, 0xe1, 0xe4, 0x58, 0x6a, 0xc6, 0x2d,
	0xd5, 0xe2, 0x59, 0xed, 0x43, 0x33, 0x79, 0x3d, 0xbf, 0x6f, 0xd8, 0x4d, 0xa8, 0xf8, 0x9d, 0xbb,
	0x6a, 0x84, 0x52, 0x16, 0x25, 0x61, 0xeb, 0x55, 0x2a, 0x4a, 0xbe, 0x72, 0xe9, 0xbe, 0x48, 0xfb,
	0x4d, 0x06, 0xe5, 0xb1, 0xed, 0x11, 0x6a, 0xe0, 0x1e, 0x11, 0xae, 0x58, 0xd3, 0x9c, 0x8f, 0xfe,
	0xfe, 0xb2, 0xa0, 0xbf, 0xb7, 0x84, 0x7a, 0x11, 0x33, 0x67, 0xd3, 0xe7, 0xbf, 0x4a, 0x70, 0x25,
	0x2f, 0xa2, 0x13, 0xf5, 0xfb, 0x0c, 0x4e, 0xd1, 0x96, 0x68, 0x52, 0x3f, 0x65, 0xd7, 0x8f, 0x21,
	0xc5, 0x6f, 0x56, 0xcd, 0x80, 0xab, 0xf9, 0x41, 0x86, 0x55, 0x59, 0x66, 0xcb, 0x92, 0x88, 0x30,
	0x9d, 0x57, 0x2e, 0x9b, 0xa9, 0x72, 0x09, 0xa0, 0x4e, 0x0f, 0x5b, 0x98, 0x1e, 0x62, 0xea, 0x86,
	0x1c, 0x84, 0xd7, 0x92, 0x8a, 0xaf, 0x15, 0xe7, 0xa9, 0x74, 0x0c, 0x4f, 0xda, 0x0b, 0x68, 0x24,
	0xdc, 0x44, 0xbd, 0x75, 0xac, 0x9f, 0x59, 0x6e, 0x61, 0xc2, 0x3b, 0xbe, 0xf9, 0x0e, 0xa1, 0x26,
	0xb6, 0xcc, 0x6f, 0xdf, 0xde, 0x4d, 0x30, 0x5c, 0xca, 0xb8, 0x3a, 0xe5, 0xdb, 0xfc, 0x22, 0x43,
	0xf3, 0x0b, 0x9b, 0xb9, 0x3d, 0x6f, 0x93, 0xe4, 0x79, 0xc1, 0x24, 0xb9, 0x2b, 0xd4, 0xf3, 0x58,
	0x39, 0x9b, 0x29, 0xf2, 0xb3, 0x04, 0x97, 0xd2, 0xd1, 0xbc, 0xb5, 0x09, 0x72, 0x37, 0x31, 0x41,
	0xae, 0x4c, 0x21, 0x43, 0x4c, 0x8f, 0x2e, 0x28, 0xd9, 0xe0, 0x4e, 0x79, 0x72, 0xfc, 0x20, 0x03,
	0x74, 0x3c, 0x4a, 0xf0, 0xe0, 0x7c, 0xd4, 0xe6, 0x93, 0x82, 0xda, 0xbc, 0x1d, 0xec, 0xfc, 0x21,
	0x17, 0x67, 0x53, 0x91, 0x3f, 0xca, 0x70, 0xc1, 0x8f, 0xe1, 0x44, 0x75, 0xb8, 0x9d, 0xfd, 0x8e,
	0xbd, 0x99, 0xb8, 0xd9, 0xf1, 0xdb, 0xe8, 0xed, 0x44, 0x99, 0xae, 0x64, 0x78, 0x11, 0x7b, 0xe8,
	0x47, 0xd1, 0x1e, 0xea, 0x7f, 0x69, 0xdd, 0xc8, 0xf5, 0x73, 0xfc, 0x06, 0x5a, 0xf9, 0x5f, 0x6c,
	0xa0, 0x2f, 0x82, 0xb4, 0x3c, 0x21, 0xae, 0x8b, 0x8f, 0x4e, 0x7b, 0xf5, 0x6c, 0xc0, 0xca, 0xce,
	0xc4, 0x23, 0x09, 0xee, 0xb4, 0x16, 0x40, 0x74, 0xc8, 0x3e, 0x9f, 0xfb, 0xd8, 0xc3, 0xdc, 0x59,
	0x5d, 0xe7, 0xbf, 0x37, 0xff, 0x28, 0x43, 0x75, 0x97, 0xff, 0x03, 0x18, 0x3d, 0x82, 0x7a, 0x7c,
	0x45, 0x46, 0x6a, 0xf1, 0x67, 0x81, 0x7a, 0x25, 0x57, 0x26, 0xc2, 0x7d, 0x09, 0xcd, 0xbc, 0x9d,
	0x05, 0x69, 0x53, 0x56, 0x9e, 0xc0, 0xf0, 0xcd, 0xa9, 0x18, 0xe1, 0x60, 0x17, 0x16, 0x63, 0x5b,
	0x04, 0x0a, 0xbe, 0xf2, 0xb3, 0x0b, 0x8c, 0xaa, 0xe6, 0x89, 0x84, 0x95, 0x43, 0xb8, 0x98, 0x7a,
	0x83, 0xa3, 0x6b, 0x09, 0x78, 0x7a, 0x89, 0x50, 0x57, 0x8b, 0xc4, 0xc2, 0x62, 0x07, 0x96, 0xd3,
	0xe3, 0x16, 0xad, 0x16, 0x4c, 0xe9, 0xc0, 0xe6, 0xf5, 0x42, 0xb9, 0x30, 0xfa, 0x3e, 0x54, 0x45,
	0xfe, 0x9a, 0x79, 0xfd, 0xa1, 0x26, 0x4f, 0x45, 0x71, 0x6d, 0x48, 0xe8, 0x03, 0xa6, 0xd7, 0x77,
	0x46, 0x1e, 0x52, 0x04, 0x22, 0x53, 0x1f, 0xea, 0x4a, 0x46, 0x12, 0x2a, 0x12, 0x4a, 0x5f, 0x53,
	0xb1, 0x5b, 0xe5, 0x67, 0x5b, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x94, 0x65, 0x1f, 0x7c, 0x52,
	0x18, 0x00, 0x00,
}
