on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
name: Stucco release
env:
  CGO_ENABLED: 0
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - platform: ubuntu-latest
            goos: linux
            goarch: amd64
          - platform: macos-latest
            goos: darwin
            goarch: amd64
          - platform: windows-latest
            goos: windows
            goarch: amd64
            ext: '.exe'
    runs-on: ${{ matrix.platform }}
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v1
    - name: version
      id: version
      uses: frabert/replace-string-action@v1.1
      with:
        pattern: 'refs/tags/(.*)'
        string: '${{ github.ref }}'
        replace-with: '$1'
    - name: cache deps
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: build all
      run: go build ./pkg/... ./stucco/...
    - name: build stucco
      run: go build -ldflags="-X github.com/graphql-editor/stucco/pkg/version.Version=${{ steps.version.outputs.replaced }}" -o bin/${{ steps.version.outputs.replaced }}/${{ matrix.goos }}/${{ matrix.goarch }}/stucco${{ matrix.ext }} ./stucco
    - name: test
      env:
        CGO_ENABLED: 1
      run: |
        go test ./...
        go test -race ./...
    - uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: bin
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: pull artifacts
      uses: actions/download-artifact@v1
      with:
        name: binaries
        path: bin
    - name: version
      id: version
      uses: frabert/replace-string-action@v1.1
      with:
        pattern: 'refs/tags/(.*)'
        string: '${{ github.ref }}'
        replace-with: '$1'
    - name: copy latest version
      run: |
        cp -r bin/${{ steps.version.outputs.replaced }} bin/latest
    - name: latest version tag
      run: |
        echo "${{ steps.version.outputs.replaced }}" > bin/latest/version
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: 'stucco-release'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT: 'https://fra1.digitaloceanspaces.com'
        AWS_REGION: 'fra1'
        SOURCE_DIR: 'bin'
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true
        body: |
          Download links and changes from previous version available in [CHANGELOG.md](https://github.com/graphql-editor/stucco/blob/${{ steps.version.outputs.replaced }}/CHANGELOG.md)
